service: lists3evan

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: us-east-1
  deploymentBucket: evandangol
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "*"
      Resource: "*"
        


functions:
  start:
    handler: handler.start
