service: nodeserverless
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
         - "/*"

  iamRoleStatements:  # 1
    - Effect: Allow  # 2
      Action: S3:ListBucket  # 3
      Resource: arn:aws:s3:::evansite  # 4       
functions:
  hello:
    handler: handler.hello
    events:  # 1
      - http:  # 2
          method: get  # 3
          path: hello  # 4
